set "NOLOgo="
set "name=%~n1"
set "abc=%name:&=^&%"
if not "%abc:­™“‡ƒeƒŒƒr•ú‘—=%" == "%abc%" set "NOLOgo=NOLOgo"
if not "%abc:­™“‡æ¤æÌƒeƒŒƒr=%" == "%abc%" set "NOLOgo=NOLOgo"
if not "%abc:‚j‚s‚r­™“‡ƒeƒŒƒr=%" == "%abc%" set "NOLOgo=NOLOgo"
if not "%abc:‚m‚g‚j‚dƒeƒŒ=%" == "%abc%" set "NOLOgo=nhke"
if not "%abc:‚m‚g‚j‘‡=%" == "%abc%" set "NOLOgo=nhkg"
if not "%abc:‚a‚rƒeƒŒ“Œ=%" == "%abc%" set "NOLOgo=bstvtokyo"
if not "%abc:‚a‚rƒWƒƒƒpƒ“=%" == "%abc%" set "NOLOgo=bstvtokyo"
if not "%abc:‚l‚a‚b“ì“ú–{•ú‘—=%" == "%abc%" set "NOLOgo=mbc"
if not "%abc:‚m‚g‚j‚a‚r‚P=%" == "%abc%" set "NOLOgo=nhkbs1"
if not "%abc:‚m‚g‚j‚a‚rƒvƒŒƒ~ƒAƒ€=%" == "%abc%" set "NOLOgo=nhkbsp"
if not "%abc:‚a‚rƒtƒWE‚P‚W‚P=%" == "%abc%" set "NOLOgo=bsfuji"
if not "%abc:‚a‚r‚P‚PƒCƒŒƒuƒ“=%" == "%abc%" set "NOLOgo=bs11"
if not "%abc:‚j‚j‚a­™“‡•ú‘—=%" == "%abc%" set "NOLOgo=kkb"
if not "%abc:•ú‘—‘åŠw=%" == "%abc%" set "NOLOgo=housou"
if not "%abc:‚a‚r‚i‚‚‚‚‚…‚˜‚”=%" == "%abc%" set "NOLOgo=bsjapanext"
if not "%abc:‚a‚r’©“ú‚P=%" == "%abc%" set "NOLOgo=bsa"
if not "%abc:‚a‚r|‚s‚a‚r=%" == "%abc%" set "NOLOgo=bstbs"
if not "%abc:‚a‚r“úƒeƒŒ=%" == "%abc%" set "NOLOgo=bs4"
if not "%abc:‚a‚r‚P‚QƒgƒDƒGƒ‹ƒr=%" == "%abc%" set "NOLOgo=twellv"
if not "%abc:‚s‚—‚…‚Œ‚Œ‚u=%" == "%abc%" set "NOLOgo=twellv"
exit /b 0
